//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeightTerminal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_ScaleTerminal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ScaleTerminal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeightTerminal.Properties.Resources.ScaleTerminal", typeof(Resources_ScaleTerminal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Килограммы.
        /// </summary>
        internal static string MassUnit_kg_Description {
            get {
                return ResourceManager.GetString("MassUnit.kg.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тонны.
        /// </summary>
        internal static string MassUnit_tn_Description {
            get {
                return ResourceManager.GetString("MassUnit.tn.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HBM WE2110: HBM стандартный формат.
        /// </summary>
        internal static string TerminalType_HbmWe2110_Description {
            get {
                return ResourceManager.GetString("TerminalType.HbmWe2110.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Микросим М0601.
        /// </summary>
        internal static string TerminalType_MicrosimM0601_Description {
            get {
                return ResourceManager.GetString("TerminalType.MicrosimM0601.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МИДЛ МИ ВДА/12Я.
        /// </summary>
        internal static string TerminalType_MidlVda12_Description {
            get {
                return ResourceManager.GetString("TerminalType.MidlVda12.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ньютон-42.
        /// </summary>
        internal static string TerminalType_Newton42_Description {
            get {
                return ResourceManager.GetString("TerminalType.Newton42.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ньютон-42: сжатая двоичная посылка.
        /// </summary>
        internal static string TerminalType_Newton42Byte_Description {
            get {
                return ResourceManager.GetString("TerminalType.Newton42Byte.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключено.
        /// </summary>
        internal static string TerminalType_None_Description {
            get {
                return ResourceManager.GetString("TerminalType.None.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Токвес SH-50.
        /// </summary>
        internal static string TerminalType_TokvesSh50_Description {
            get {
                return ResourceManager.GetString("TerminalType.TokvesSh50.Description", resourceCulture);
            }
        }
    }
}
