//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeightTerminal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesLog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesLog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeightTerminal.Properties.ResourcesLog", typeof(ResourcesLog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check settings: terminaltype=none.
        /// </summary>
        internal static string CheckSettingsTerminalNone {
            get {
                return ResourceManager.GetString("CheckSettingsTerminalNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com ports count: {0}.
        /// </summary>
        internal static string ComPortsCount {
            get {
                return ResourceManager.GetString("ComPortsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com port not found.
        /// </summary>
        internal static string ComPortsNotExists {
            get {
                return ResourceManager.GetString("ComPortsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app directory.
        /// </summary>
        internal static string PathAppDirectory {
            get {
                return ResourceManager.GetString("PathAppDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to database.
        /// </summary>
        internal static string PathDatabase {
            get {
                return ResourceManager.GetString("PathDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data directory.
        /// </summary>
        internal static string PathDataDirectory {
            get {
                return ResourceManager.GetString("PathDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created.
        /// </summary>
        internal static string PathDataDirectoryCreateOk {
            get {
                return ResourceManager.GetString("PathDataDirectoryCreateOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logs directory.
        /// </summary>
        internal static string PathLogsDirectory {
            get {
                return ResourceManager.GetString("PathLogsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        internal static string PathSettings {
            get {
                return ResourceManager.GetString("PathSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} closed.
        /// </summary>
        internal static string ScaleTerminalClosed {
            get {
                return ResourceManager.GetString("ScaleTerminalClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} opened. type = {1}.
        /// </summary>
        internal static string ScaleTerminalOpened {
            get {
                return ResourceManager.GetString("ScaleTerminalOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        internal static string UpdateDone {
            get {
                return ResourceManager.GetString("UpdateDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        internal static string UpdateStart {
            get {
                return ResourceManager.GetString("UpdateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current: {0}, latest: {1}.
        /// </summary>
        internal static string UpdateVersions {
            get {
                return ResourceManager.GetString("UpdateVersions", resourceCulture);
            }
        }
    }
}
