//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeightTerminal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeightTerminal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл должен находиться в каталоге c номером версии, например, {0}..
        /// </summary>
        internal static string AppUpdateErrorFileWrongLocation {
            get {
                return ResourceManager.GetString("AppUpdateErrorFileWrongLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось проверить или установить обновление.
        ///Ошибка:
        ///{0}.
        /// </summary>
        internal static string AppUpdateErrorInProgress {
            get {
                return ResourceManager.GetString("AppUpdateErrorInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установлена актуальная версия..
        /// </summary>
        internal static string AppUpdateInfoAlreadyLatest {
            get {
                return ResourceManager.GetString("AppUpdateInfoAlreadyLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процесс обновления уже запущен..
        /// </summary>
        internal static string AppUpdateInfoInProgress {
            get {
                return ResourceManager.GetString("AppUpdateInfoInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск обновления.
        /// </summary>
        internal static string AppUpdateInfoStatusCheckLatest {
            get {
                return ResourceManager.GetString("AppUpdateInfoStatusCheckLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка обновления.
        /// </summary>
        internal static string AppUpdateInfoStatusDownload {
            get {
                return ResourceManager.GetString("AppUpdateInfoStatusDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установка обновления.
        /// </summary>
        internal static string AppUpdateInfoStatusExtract {
            get {
                return ResourceManager.GetString("AppUpdateInfoStatusExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить обновления.
        /// </summary>
        internal static string AppUpdateInfoStatusIdle {
            get {
                return ResourceManager.GetString("AppUpdateInfoStatusIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа обновлена. Перезапустите для применения обновления..
        /// </summary>
        internal static string AppUpdateInfoUpdated {
            get {
                return ResourceManager.GetString("AppUpdateInfoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Происходит процесс обновления. Прервать?.
        /// </summary>
        internal static string AppUpdateQuestionInProgress {
            get {
                return ResourceManager.GetString("AppUpdateQuestionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка:
        ///{0}.
        /// </summary>
        internal static string ErrorError {
            get {
                return ResourceManager.GetString("ErrorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка:
        ///Не указан порт, к которому подключен терминал..
        /// </summary>
        internal static string ErrorTerminalPortEmpty {
            get {
                return ResourceManager.GetString("ErrorTerminalPortEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка:
        ///Не указан тип весового терминала..
        /// </summary>
        internal static string ErrorTerminalTypeNone {
            get {
                return ResourceManager.GetString("ErrorTerminalTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/P3tr0viCh/WeightTerminal.
        /// </summary>
        internal static string GitHubLink {
            get {
                return ResourceManager.GetString("GitHubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string ToolTipKey {
            get {
                return ResourceManager.GetString("ToolTipKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть подключение.
        /// </summary>
        internal static string ToolTipStateClosing {
            get {
                return ResourceManager.GetString("ToolTipStateClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть подключение.
        /// </summary>
        internal static string ToolTipStateOpening {
            get {
                return ResourceManager.GetString("ToolTipStateOpening", resourceCulture);
            }
        }
    }
}
